version: '3.8'

services:
  django_backend:
    build:
      context: ./django_backend
      dockerfile: Dockerfile.prod
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/django_backend/web/static
      - media_volume:/home/django_backend/web/media
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db


volumes:
  postgres_data_prod:
  static_volume:
  media_volume:
