# Generated by Django 3.2.9 on 2021-12-31 10:43

import ckeditor_uploader.fields
import datetime
from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.citext
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning', '0002_alter_learning_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('status', models.CharField(choices=[('Published', 'Published'), ('Draft', 'Draft'), ('Trash', 'Trash')], max_length=50)),
                ('view', models.BigIntegerField(blank=True, default=0, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='blog')),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.citext.CICharField(max_length=20), blank=True, size=None)),
                ('pub_date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('type', models.CharField(choices=[('Free', 'Free'), ('Paid', 'Paid')], max_length=10)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='learning.category')),
                ('purchaser', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Learning',
        ),
    ]
