# Generated by Django 3.2.11 on 2022-01-28 04:53

import django.core.files.storage
from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='attachment',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/attachment/', location=pathlib.PurePosixPath('/django_backend/learning_attachments')), upload_to=''),
        ),
    ]
