# Generated by Django 3.2.12 on 2022-03-12 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_alter_post_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(upload_to='learning/picture'),
        ),
    ]
