# Generated by Django 3.2.11 on 2022-01-20 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_alter_post_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='learning/attachment'),
        ),
    ]
