# Generated by Django 3.2.11 on 2022-01-20 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_alter_post_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='learning/picture'),
        ),
    ]
