# Generated by Django 3.2.11 on 2022-01-21 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_alter_post_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.DecimalField(decimal_places=0, default=100000, max_digits=12),
            preserve_default=False,
        ),
    ]
