# Generated by Django 3.2.11 on 2022-01-26 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0009_alter_post_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='type',
        ),
        migrations.AddField(
            model_name='post',
            name='max_order_quantity',
            field=models.DecimalField(decimal_places=0, default=10, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='min_order_quantity',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
            preserve_default=False,
        ),
    ]
