# Generated by Django 3.2.12 on 2022-03-11 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('expired_at', models.DateTimeField(blank=True, null=True, verbose_name='expired at')),
                ('due_at', models.DateTimeField(blank=True, null=True, verbose_name='due at')),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True, verbose_name='fulfilled at')),
                ('amount', models.PositiveIntegerField(default=0, verbose_name='amount')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'initial'), (2, 'processing'), (3, 'confirmed')], default=1, verbose_name='status')),
                ('status_change_date', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.order', verbose_name='order')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
