# Generated by Django 3.2.11 on 2022-01-21 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status_change_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
