# Generated by Django 3.2.11 on 2022-01-20 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_cart_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='object_id',
            new_name='object_pk',
        ),
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('T', 'Transferred'), ('F', 'Failed')], default='P', max_length=20),
        ),
    ]
