# Generated by Django 3.2.12 on 2022-03-12 05:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0002_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='purchaser',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
