# Generated by Django 3.2.11 on 2022-01-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_cart_status_change_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=0, max_digits=18, verbose_name='unit price'),
        ),
    ]
