# Generated by Django 3.2.11 on 2022-01-29 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_cartitem_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='content_type',
            new_name='product',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='object_pk',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
    ]
