# Generated by Django 3.2.11 on 2022-01-25 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_cartitem_unit_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='object_title',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='unit_price',
        ),
    ]
