# Generated by Django 3.2.11 on 2022-01-29 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order_order_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_number',
        ),
    ]
