# Generated by Django 3.2.11 on 2022-01-27 09:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20220127_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=0, default=Decimal('10'), max_digits=12),
        ),
    ]
