# Generated by Django 3.2.9 on 2021-12-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='mobile',
            field=models.TextField(default='00989123456789', max_length=20, verbose_name='mobile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.TextField(default='00982112345678', max_length=20, verbose_name='mobile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.TextField(default='your address', max_length=250, verbose_name='address'),
        ),
    ]
