# Generated by Django 3.2.9 on 2021-12-09 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
