# Generated by Django 3.2.9 on 2021-12-09 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0002_rename_phone_number_message_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='checked',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], db_column='Read', default='No', max_length=50),
        ),
    ]
