# Generated by Django 3.2.9 on 2021-12-09 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0003_alter_message_checked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='message',
            name='owner',
        ),
    ]
